version: '3'

services:
  srv1:
    &server-configuration
    image: habitat/builder-minio:latest
    command: --peer srv1
    environment:
      HAB_BUILDER_MINIO: |
        standalone = false
        members = [
          "http://srv1/hab/svc/builder-minio/data",
          "http://srv2/hab/svc/builder-minio/data",
          "http://srv3/hab/svc/builder-minio/data",
          "http://srv4/hab/svc/builder-minio/data",
        ]
    ports:
      - "9000"
  srv2:
    *server-configuration
  srv3:
    *server-configuration
  srv4:
    *server-configuration
