#!/bin/bash

# Given an "environment", generates a tmuxinator YAML on STDOUT to
# connect to all the Biome Builder hosts in that environment.

set -euo pipefail

environment=${1}

# Note: if no hosts are found (and thus no windows generated),
# tmuxinator will refuse to start, which is nice.

echo "# Auto-generated by bio-env. All manual edits will be lost!"
echo "name: bio_${environment}"
echo "windows:"
# shellcheck disable=2013
for host in $(grep "Host ${environment}-builder" ~/.ssh/config | awk '{print $2}' | sort)
do
    title=${host#"${environment}"-builder-}
    echo "  - ${title}:"
    echo "    - ssh $host"
done
