[package]
name = "artifactory-client"
version = "0.0.0"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"
edition = "2018"

[dependencies]
env_proxy = "*"
reqwest = "0.8.1"
log = "*"
serde = "*"
serde_derive = "*"
hyper = "0.11"
url = "*"

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/habitat.git"
