name: release

on:
  release:
    types: [published]

jobs:

  package-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Linux Biome
        run: |
          curl https://raw.githubusercontent.com/biome-sh/biome/master/components/bio/install-linux.sh | sudo bash

      - name: Install Signing Keys
        env:
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
        run: |
          bio origin key download biome
          bio origin key download -s biome

      - name: Setup Studio and Tools
        env:
          HAB_ORIGIN: biome
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
        run: |
          bio studio run 'make -f ci/Makefile setup'

      - name: Build and Package
        env:
          HAB_ORIGIN: biome
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
        run: |
          bio studio run 'make -f ci/Makefile build dist upload'

      - name: Get package info
        run: |
          cat results/builder-api.env >> $GITHUB_ENV

      - name: Upload Linux Metadata
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: results/meta-${{ env.pkg_version }}-${{ env.pkg_target }}.tar.gz
          asset_name: meta-${{ env.pkg_version }}-${{ env.pkg_target }}.tar.gz
          asset_content_type: application/gzip

      - name: Promote to testing
        env:
          HAB_ORIGIN: biome
          HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
        run: |
          bio studio run 'make -f ci/Makefile promote-testing'
