name: release

on:
  release:
    types: [published]

jobs:

  package-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          echo ::set-env name=HAB_AUTH_TOKEN::${{ secrets.HAB_AUTH_TOKEN }}
          echo ::set-env name=HAB_ORIGIN::biome

      - name: Install Linux Biome
        run: |
          curl https://raw.githubusercontent.com/biome-sh/biome/master/components/bio/install-linux.sh | sudo bash

      - name: Install Signing Keys
        run: |
          bio origin key download biome
          bio origin key download -s -z $HAB_AUTH_TOKEN biome

      - name: Setup Studio and Tools
        run: |
          bio studio run 'make -f ci/Makefile setup'

      - name: Build and Package
        run: |
          bio studio run 'make -f ci/Makefile all upload'

      - name: Get package info
        run: |
          cat results/bio.env | sed 's/\(.*\)=\(.*\)/::set-env name=\1::\2/'

      - name: Promote to testing
        run: |
          bio studio run 'make -f ci/Makefile promote-testing'
